modLoader="javafml"
license="LGPLv3"
loaderVersion="[39,)"
issueTrackerURL="https://github.com/Glitchfiend/TerraBlender/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/terrablender"
logoFile="tb_logo.png"

[[mods]]
    modId="terrablender"
    version="${file.jarVersion}"
    displayName="TerraBlender"
	authors="Adubbz"
    description="A library mod for adding biomes in a simple and compatible manner with Minecraft's new biome/terrain system."

[[dependencies.terrablender]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.64,)"
    ordering="NONE"
    side="BOTH"